INSERT INTO developers (name, age, country, city, join_date) VALUES ('Semen',   20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Ivan',    20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Elena',   20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Nata',    20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Igor',    20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Andrey',  20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Nastya',  20, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Grigoriy',25, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Anna',    25, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Iryna',   25, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Alex',    25, 'Ukraine', 'Kiev',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Artem',   25, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Alla',    25, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Maria',   25, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Alyona',  25, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Evgeniy', 18, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Slava',   18, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Stas',    18, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Alexandr',18, 'Ukraine', 'Lviv',   '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Inna',    18, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Igor',    18, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Vasyliy', 28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Yakov',   28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Lyly',    28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Eleanora',28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Nick',    28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Ilya',    28, 'Ukraine', 'Odessa', '2017-12-02');
INSERT INTO developers (name, age, country, city, join_date) VALUES ('Elly',    28, 'Ukraine', 'Odessa', '2017-12-02');

INSERT INTO skills(skill_description) VALUES ('Java');
INSERT INTO skills(skill_description) VALUES ('C#');
INSERT INTO skills(skill_description) VALUES ('JavaScript');
INSERT INTO skills(skill_description) VALUES ('C++');
INSERT INTO skills(skill_description) VALUES ('Python');
INSERT INTO skills(skill_description) VALUES ('Scala');
INSERT INTO skills(skill_description) VALUES ('PHP');
INSERT INTO skills(skill_description) VALUES ('Perl');

INSERT INTO dev_skills VALUES (1, 1);
INSERT INTO dev_skills VALUES (1, 4);
INSERT INTO dev_skills VALUES (2, 4);
INSERT INTO dev_skills VALUES (3, 3);
INSERT INTO dev_skills VALUES (4, 6);
INSERT INTO dev_skills VALUES (5, 8);
INSERT INTO dev_skills VALUES (6, 6);
INSERT INTO dev_skills VALUES (7, 4);
INSERT INTO dev_skills VALUES (7, 2);
INSERT INTO dev_skills VALUES (7, 7);
INSERT INTO dev_skills VALUES (8, 1);
INSERT INTO dev_skills VALUES (8, 5);
INSERT INTO dev_skills VALUES (9, 1);
INSERT INTO dev_skills VALUES (10, 1);
INSERT INTO dev_skills VALUES (11, 1);
INSERT INTO dev_skills VALUES (12, 1);
INSERT INTO dev_skills VALUES (13, 3);
INSERT INTO dev_skills VALUES (13, 1);
INSERT INTO dev_skills VALUES (14, 4);
INSERT INTO dev_skills VALUES (15, 4);
INSERT INTO dev_skills VALUES (16, 6);
INSERT INTO dev_skills VALUES (17, 6);
INSERT INTO dev_skills VALUES (17, 8);
INSERT INTO dev_skills VALUES (18, 8);
INSERT INTO dev_skills VALUES (19, 7);
INSERT INTO dev_skills VALUES (20, 7);
INSERT INTO dev_skills VALUES (21, 2);
INSERT INTO dev_skills VALUES (22, 2);
INSERT INTO dev_skills VALUES (23, 2);
INSERT INTO dev_skills VALUES (24, 1);
INSERT INTO dev_skills VALUES (25, 5);
INSERT INTO dev_skills VALUES (26, 5);
INSERT INTO dev_skills VALUES (26, 8);
INSERT INTO dev_skills VALUES (27, 5);
INSERT INTO dev_skills VALUES (28, 5);

INSERT INTO companies(name, address, country, city) VALUES ('Luxoft', 'adr1', 'Ukraine', 'Kiev');
INSERT INTO companies(name, address, country, city) VALUES ('Goggle', 'adr2', 'USA','Mountain View');
INSERT INTO companies(name, address, country, city) VALUES ('Ciklum', 'adr3', 'Ukraine', 'Kiev');
INSERT INTO companies(name, address, country, city) VALUES ('GlobalLogic', 'adr4', 'Ukraine', 'Kiev');

INSERT INTO projects(name, description) VALUES ('ProjectX', 'project1');
INSERT INTO projects(name, description) VALUES ('Google Pixel', 'project2');
INSERT INTO projects(name, description) VALUES ('Google Soli', 'project3');
INSERT INTO projects(name, description) VALUES ('PayCash', 'project4');
INSERT INTO projects(name, description) VALUES ('BIScience', 'project5');
INSERT INTO projects(name, description) VALUES ('PayCash2', 'project6');
INSERT INTO projects(name, description) VALUES ('BIScience3', 'project7');
INSERT INTO projects(name, description) VALUES ('TechFinancials', 'project8');

INSERT INTO customers(name) VALUES ('PayCash');
INSERT INTO customers(name) VALUES ('BIScience');
INSERT INTO customers(name) VALUES ('TechFinancials');
INSERT INTO customers(name) VALUES ('Society');

INSERT INTO projects_customers VALUES (1, 3);
INSERT INTO projects_customers VALUES (2, 4);
INSERT INTO projects_customers VALUES (3, 4);
INSERT INTO projects_customers VALUES (4, 1);
INSERT INTO projects_customers VALUES (5, 2);
INSERT INTO projects_customers VALUES (6, 1);
INSERT INTO projects_customers VALUES (7, 2);
INSERT INTO projects_customers VALUES (8, 3);

INSERT INTO project_company VALUES (1, 1);
INSERT INTO project_company VALUES (2, 2);
INSERT INTO project_company VALUES (3, 2);
INSERT INTO project_company VALUES (4, 3);
INSERT INTO project_company VALUES (5, 1);
INSERT INTO project_company VALUES (6, 4);
INSERT INTO project_company VALUES (7, 1);
INSERT INTO project_company VALUES (8, 4);

INSERT INTO dev_projects VALUES (1, 1);
INSERT INTO dev_projects VALUES (2, 1);
INSERT INTO dev_projects VALUES (3, 1);
INSERT INTO dev_projects VALUES (4, 1);
INSERT INTO dev_projects VALUES (5, 1);
INSERT INTO dev_projects VALUES (6, 1);
INSERT INTO dev_projects VALUES (7, 2);
INSERT INTO dev_projects VALUES (8, 2);
INSERT INTO dev_projects VALUES (9, 2);
INSERT INTO dev_projects VALUES (10, 2);
INSERT INTO dev_projects VALUES (11, 3);
INSERT INTO dev_projects VALUES (12, 3);
INSERT INTO dev_projects VALUES (13, 4);
INSERT INTO dev_projects VALUES (14, 4);
INSERT INTO dev_projects VALUES (15, 4);
INSERT INTO dev_projects VALUES (16, 4);
INSERT INTO dev_projects VALUES (17, 5);
INSERT INTO dev_projects VALUES (18, 5);
INSERT INTO dev_projects VALUES (19, 6);
INSERT INTO dev_projects VALUES (20, 6);
INSERT INTO dev_projects VALUES (21, 6);
INSERT INTO dev_projects VALUES (22, 7);
INSERT INTO dev_projects VALUES (23, 7);
INSERT INTO dev_projects VALUES (24, 7);
INSERT INTO dev_projects VALUES (25, 7);
INSERT INTO dev_projects VALUES (26, 7);
INSERT INTO dev_projects VALUES (27, 7);
INSERT INTO dev_projects VALUES (28, 8);